# После изменений в этом файле нужно перезапускать jekyll

# Заголовок
title: Курс ДПП «Разработка приложений на языке Python»

# Если сайт расположен в подкаталоге, например /blog/<сайт>
# baseurl: ""

# Адрес сайта
# url: "https://dpp-svfu-python.github.io"

# Готовая тема оформления https://github.com/jekyll/minima
# theme: minima

# В теме minima доступны 4 типа страниц (layout):
# * base - базовый, 
# * home - стартовая страница сайта
# * page - страницы, которые не пост блога
# * post - посты блога

# plugins:
  # - jekyll-feed

# Настройки темы
# lang: ru
# author:
  # name:
  # email:

# email: your-email@example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Описание в нижней части
# description: >- # this means to ignore newlines until "baseurl:"
  # Сайт курса ДПП «Разработка приложений на языке программирования Python»

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

timezone: Asia/Yakutsk
