# После изменений в этом файле нужно перезапускать jekyll

# Заголовок
title: Курс ДПП «Разработка приложений на языке Python»

# Если сайт расположен в подкаталоге, например /blog/<сайт>
baseurl: ""

# Адрес сайта
url: "https://dpp-svfu-python.github.io"

# Готовая тема оформления https://github.com/jekyll/minima
theme: minima

# В теме minima доступны 4 типа страниц (layout):
# * base - базовый, 
# * home - стартовая страница сайта
# * page - страницы, которые не пост блога
# * post - посты блога

plugins:
  - jekyll-feed

# Настройки темы
lang: ru
author:
  name:
  email:

# email: your-email@example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Описание в нижней части
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
